CREATE TABLE IF NOT EXISTS gamemodel (
id PRIMARY KEY AUTOINCREMENT,
title	TEXT NOT NULL,
price	REAL,
picture_url TEXT,
description TEXT,
rating REAL,
release_date TEXT,
);

CREATE TABLE IF NOT EXISTS tagmodel (
id INTEGER NOT NULL,
tag TEXT NOT NULL,
PRIMARY KEY (id, tag),
);

CREATE TABLE IF NOT EXISTS user_model (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS registered_user_model (
id INTEGER PRIMARY KEY AUTOINCREMENT,
banned BOOLEAN NOT NULL,
is_admin BOOLEAN NOT NULL,
name TEXT NOT NULL UNIQUE,
passhash TEXT NOT NULL
);