CREATE TABLE IF NOT EXISTS Game (
Id PRIMARY KEY AUTOINCREMENT,
Title	TEXT NOT NULL,
Price	REAL,
PictureURL TEXT,
Description TEXT,
Rating REAL,
ReleaseDate TEXT,
);

CREATE TABLE IF NOT EXISTS GameTag (
GameId INTEGER NOT NULL,
Tag TEXT NOT NULL,
PRIMARY KEY (GameId, Tag),
FOREIGN KEY (GameId) REFERENCES Game(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS User (
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS UserGame (
UserId INTEGER NOT NULL,
GameId INTEGER NOT NULL,
PRIMARY KEY (UserId, GameId),
FOREIGN KEY (UserId) REFERENCES User(Id) ON DELETE CASCADE,
FOREIGN KEY (GameId) REFERENCES Game(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RegisteredUser (
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Banned BOOLEAN NOT NULL,
IsAdmin BOOLEAN NOT NULL,
LoginName TEXT NOT NULL UNIQUE,
PassHash TEXT NOT NULL
);